// Server-only. Templates for the files we commit into the user's repo.

export const WORKFLOW_YML = `name: Lovable Coder
on:
  repository_dispatch:
    types: [lovable-coding-job]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    permissions:
      contents: write
    steps:
      - name: Mask job secret
        run: echo "::add-mask::\${{ github.event.client_payload.job_secret }}"
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.event.client_payload.working_branch }}
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Lovable coder
        env:
          JOB_ID: \${{ github.event.client_payload.job_id }}
          JOB_SECRET: \${{ github.event.client_payload.job_secret }}
          APP_URL: \${{ github.event.client_payload.app_url }}
          WORKING_BRANCH: \${{ github.event.client_payload.working_branch }}
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: node scripts/lovable-coder/runner.mjs
`;

export const RUNNER_MJS = `#!/usr/bin/env node
// Auto-generated by Lovable. Runs a single coding job driven by the app.
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const JOB_ID = process.env.JOB_ID;
const JOB_SECRET = process.env.JOB_SECRET;
const APP_URL = process.env.APP_URL;
const BRANCH = process.env.WORKING_BRANCH;
const GH_TOKEN = process.env.GH_TOKEN;

if (!JOB_ID || !JOB_SECRET || !APP_URL) { console.error("missing env"); process.exit(1); }

const HEAD = { "Content-Type": "application/json", "X-Job-Id": JOB_ID, "X-Job-Secret": JOB_SECRET };
const api = (p, body) => fetch(APP_URL + p, { method: "POST", headers: HEAD, body: JSON.stringify(body ?? {}) })
  .then(async (r) => { if (!r.ok) throw new Error(p + " " + r.status + " " + (await r.text())); return r.json(); });

const log = async (line) => { console.log(line); try { await api("/api/public/jobs/log", { line }); } catch {} };

const sh = (cmd, opts = {}) => execSync(cmd, { stdio: ["pipe", "pipe", "pipe"], encoding: "utf8", ...opts });

const MAX_STEPS = 40;
const START = Date.now();
const TIME_LIMIT_MS = 1000 * 60 * 60 * 5.5; // 5.5h, checkpoint before the 6h wall

function readFileSafe(p) {
  try { return fs.readFileSync(p, "utf8"); } catch (e) { return null; }
}
function listDir(p) {
  try { return fs.readdirSync(p, { withFileTypes: true }).map((d) => d.name + (d.isDirectory() ? "/" : "")); }
  catch (e) { return null; }
}
function writeFileSafe(p, content) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content, "utf8");
}

const tools = [
  { type: "function", function: { name: "read_file", description: "Read a text file from the repo. Returns file contents or an error string.",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "list_dir", description: "List entries in a directory (trailing slash = directory).",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "write_file", description: "Create or overwrite a file with the given content.",
    parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } },
  { type: "function", function: { name: "delete_file", description: "Delete a file.",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "run_shell", description: "Run a shell command from the repo root. Returns combined stdout+stderr (truncated).",
    parameters: { type: "object", properties: { cmd: { type: "string" } }, required: ["cmd"] } } },
  { type: "function", function: { name: "finish", description: "Call when the task is done. Provide a short summary and commit message.",
    parameters: { type: "object", properties: { summary: { type: "string" }, commit_message: { type: "string" } }, required: ["summary", "commit_message"] } } },
];

function execTool(name, args) {
  try {
    if (name === "read_file") { const c = readFileSafe(args.path); return c == null ? "ERR: not found" : c.slice(0, 60000); }
    if (name === "list_dir")  { const e = listDir(args.path); return e == null ? "ERR: not found" : e.join("\\n"); }
    if (name === "write_file"){ writeFileSafe(args.path, args.content); return "OK"; }
    if (name === "delete_file"){ fs.unlinkSync(args.path); return "OK"; }
    if (name === "run_shell") { const out = sh(args.cmd); return out.slice(0, 8000); }
    return "ERR: unknown tool";
  } catch (e) { return "ERR: " + (e?.stderr?.toString?.() ?? e.message ?? String(e)).slice(0, 4000); }
}

async function main() {
  await log("Claiming job " + JOB_ID);
  const spec = await api("/api/public/jobs/claim");
  // spec: { job_type, prompt, model, openrouter_key, mistral_key, system, messages, repo, working_branch }
  await log("Model: " + spec.model);

  if (spec.job_type === "index") { await runIndex(spec); return; }

  const messages = [
    { role: "system", content: spec.system },
    ...spec.messages,
  ];

  let done = null;
  for (let step = 0; step < MAX_STEPS; step++) {
    if (Date.now() - START > TIME_LIMIT_MS) { await log("Time limit approaching; checkpointing."); break; }
    await log("Step " + (step + 1));
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: "Bearer " + spec.openrouter_key },
      body: JSON.stringify({ model: spec.model, messages, tools, tool_choice: "auto" }),
    });
    if (!res.ok) { await log("OpenRouter error " + res.status + ": " + (await res.text()).slice(0, 500)); throw new Error("model call failed"); }
    const body = await res.json();
    const msg = body.choices?.[0]?.message;
    if (!msg) throw new Error("no message");
    messages.push(msg);
    const calls = msg.tool_calls ?? [];
    if (calls.length === 0) { if (msg.content) await log("AI: " + String(msg.content).slice(0, 400)); done = { summary: msg.content ?? "done", commit_message: "Lovable coder update" }; break; }
    for (const c of calls) {
      let args = {}; try { args = JSON.parse(c.function.arguments || "{}"); } catch {}
      const name = c.function.name;
      await log("→ " + name + " " + (args.path ?? args.cmd ?? "").toString().slice(0, 80));
      if (name === "finish") { done = { summary: args.summary, commit_message: args.commit_message }; messages.push({ role: "tool", tool_call_id: c.id, content: "ok" }); break; }
      const out = execTool(name, args);
      messages.push({ role: "tool", tool_call_id: c.id, content: out });
    }
    if (done) break;
  }

  // Commit and push whatever changed
  try {
    sh("git config user.email 'lovable-coder@users.noreply.github.com'");
    sh("git config user.name 'Lovable Coder'");
    const status = sh("git status --porcelain");
    if (status.trim().length > 0) {
      sh("git add -A");
      sh("git commit -m " + JSON.stringify(done?.commit_message ?? "Lovable coder update"));
      sh("git push origin " + BRANCH);
      const sha = sh("git rev-parse HEAD").trim();
      await log("Pushed " + sha);
      await api("/api/public/jobs/complete", { status: "completed", summary: done?.summary ?? "done", commit_sha: sha });
    } else {
      await log("No file changes.");
      await api("/api/public/jobs/complete", { status: "completed", summary: done?.summary ?? "No changes." });
    }
  } catch (e) {
    await log("Commit/push failed: " + (e.message ?? e));
    await api("/api/public/jobs/complete", { status: "failed", error: String(e.message ?? e) });
    process.exit(1);
  }
}

main().catch(async (e) => { await log("FATAL " + (e.message ?? e)); try { await api("/api/public/jobs/complete", { status: "failed", error: String(e.message ?? e) }); } catch {} process.exit(1); });
`;