// Server-only. Templates for the files we commit into the user's repo.

export const WORKFLOW_YML = `name: Lovable Coder
on:
  repository_dispatch:
    types: [lovable-coding-job]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    permissions:
      contents: write
    steps:
      - name: Mask job secret
        run: echo "::add-mask::\${{ github.event.client_payload.job_secret }}"
      - uses: actions/checkout@v4
        with:
          ref: \${{ github.event.client_payload.working_branch }}
          fetch-depth: 0
          token: \${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Lovable coder
        env:
          JOB_ID: \${{ github.event.client_payload.job_id }}
          JOB_SECRET: \${{ github.event.client_payload.job_secret }}
          APP_URL: \${{ github.event.client_payload.app_url }}
          WORKING_BRANCH: \${{ github.event.client_payload.working_branch }}
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: node scripts/lovable-coder/runner.mjs
`;

export const RUNNER_MJS = `#!/usr/bin/env node
// Auto-generated by Lovable. Runs a single coding job driven by the app.
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const JOB_ID = process.env.JOB_ID;
const JOB_SECRET = process.env.JOB_SECRET;
const APP_URL = process.env.APP_URL;
const BRANCH = process.env.WORKING_BRANCH;
const GH_TOKEN = process.env.GH_TOKEN;

if (!JOB_ID || !JOB_SECRET || !APP_URL) { console.error("missing env"); process.exit(1); }

const HEAD = { "Content-Type": "application/json", "X-Job-Id": JOB_ID, "X-Job-Secret": JOB_SECRET };
const api = (p, body) => fetch(APP_URL + p, { method: "POST", headers: HEAD, body: JSON.stringify(body ?? {}) })
  .then(async (r) => { if (!r.ok) throw new Error(p + " " + r.status + " " + (await r.text())); return r.json(); });

const log = async (line) => { console.log(line); try { await api("/api/public/jobs/log", { line }); } catch {} };

const sh = (cmd, opts = {}) => execSync(cmd, { stdio: ["pipe", "pipe", "pipe"], encoding: "utf8", ...opts });

const MAX_STEPS = 40;
const START = Date.now();
const TIME_LIMIT_MS = 1000 * 60 * 60 * 5.5; // 5.5h, checkpoint before the 6h wall

function readFileSafe(p) {
  try { return fs.readFileSync(p, "utf8"); } catch (e) { return null; }
}
function listDir(p) {
  try { return fs.readdirSync(p, { withFileTypes: true }).map((d) => d.name + (d.isDirectory() ? "/" : "")); }
  catch (e) { return null; }
}
function writeFileSafe(p, content) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content, "utf8");
}

const tools = [
  { type: "function", function: { name: "read_file", description: "Read a text file from the repo. Returns file contents or an error string.",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "list_dir", description: "List entries in a directory (trailing slash = directory).",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "write_file", description: "Create or overwrite a file with the given content.",
    parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } },
  { type: "function", function: { name: "delete_file", description: "Delete a file.",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "run_shell", description: "Run a shell command from the repo root. Returns combined stdout+stderr (truncated).",
    parameters: { type: "object", properties: { cmd: { type: "string" } }, required: ["cmd"] } } },
  { type: "function", function: { name: "finish", description: "Call when the task is done. Provide a short summary and commit message.",
    parameters: { type: "object", properties: { summary: { type: "string" }, commit_message: { type: "string" } }, required: ["summary", "commit_message"] } } },
];

function execTool(name, args) {
  try {
    if (name === "read_file") { const c = readFileSafe(args.path); return c == null ? "ERR: not found" : c.slice(0, 60000); }
    if (name === "list_dir")  { const e = listDir(args.path); return e == null ? "ERR: not found" : e.join("\\n"); }
    if (name === "write_file"){ writeFileSafe(args.path, args.content); return "OK"; }
    if (name === "delete_file"){ fs.unlinkSync(args.path); return "OK"; }
    if (name === "run_shell") { const out = sh(args.cmd); return out.slice(0, 8000); }
    return "ERR: unknown tool";
  } catch (e) { return "ERR: " + (e?.stderr?.toString?.() ?? e.message ?? String(e)).slice(0, 4000); }
}

async function main() {
  await log("Claiming job " + JOB_ID);
  const spec = await api("/api/public/jobs/claim");
  // spec: { job_type, prompt, model, openrouter_key, mistral_key, system, messages, repo, working_branch }
  await log("Model: " + spec.model);

  if (spec.job_type === "index") { await runIndex(spec); return; }

  const messages = [
    { role: "system", content: spec.system },
    ...spec.messages,
  ];

  let done = null;
  for (let step = 0; step < MAX_STEPS; step++) {
    if (Date.now() - START > TIME_LIMIT_MS) { await log("Time limit approaching; checkpointing."); break; }
    await log("Step " + (step + 1));
    const useMistral = spec.model.startsWith("mistral:");
    const endpoint = useMistral ? "https://api.mistral.ai/v1/chat/completions" : "https://openrouter.ai/api/v1/chat/completions";
    const key = useMistral ? spec.mistral_key : spec.openrouter_key;
    const modelId = useMistral ? spec.model.slice("mistral:".length) : spec.model;
    const res = await fetch(endpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: "Bearer " + key },
      body: JSON.stringify({ model: modelId, messages, tools, tool_choice: "auto" }),
    });
    if (!res.ok) { await log("Model error " + res.status + ": " + (await res.text()).slice(0, 500)); throw new Error("model call failed"); }
    const body = await res.json();
    const msg = body.choices?.[0]?.message;
    if (!msg) throw new Error("no message");
    messages.push(msg);
    const calls = msg.tool_calls ?? [];
    if (calls.length === 0) { if (msg.content) await log("AI: " + String(msg.content).slice(0, 400)); done = { summary: msg.content ?? "done", commit_message: "Lovable coder update" }; break; }
    for (const c of calls) {
      let args = {}; try { args = JSON.parse(c.function.arguments || "{}"); } catch {}
      const name = c.function.name;
      await log("→ " + name + " " + (args.path ?? args.cmd ?? "").toString().slice(0, 80));
      if (name === "finish") { done = { summary: args.summary, commit_message: args.commit_message }; messages.push({ role: "tool", tool_call_id: c.id, content: "ok" }); break; }
      const out = execTool(name, args);
      messages.push({ role: "tool", tool_call_id: c.id, content: out });
    }
    if (done) break;
  }

  // Commit and push whatever changed
  try {
    sh("git config user.email 'lovable-coder@users.noreply.github.com'");
    sh("git config user.name 'Lovable Coder'");
    const status = sh("git status --porcelain");
    if (status.trim().length > 0) {
      sh("git add -A");
      sh("git commit -m " + JSON.stringify(done?.commit_message ?? "Lovable coder update"));
      sh("git push origin " + BRANCH);
      const sha = sh("git rev-parse HEAD").trim();
      await log("Pushed " + sha);
      await api("/api/public/jobs/complete", { status: "completed", summary: done?.summary ?? "done", commit_sha: sha });
    } else {
      await log("No file changes.");
      await api("/api/public/jobs/complete", { status: "completed", summary: done?.summary ?? "No changes." });
    }
  } catch (e) {
    await log("Commit/push failed: " + (e.message ?? e));
    await api("/api/public/jobs/complete", { status: "failed", error: String(e.message ?? e) });
    process.exit(1);
  }
}

// ============ Indexing mode ============
const IGNORE_DIRS = new Set(["node_modules",".git","dist","build",".next",".turbo",".cache","coverage","out",".venv","venv","target",".output"]);
const TEXT_EXT = /\\.(ts|tsx|js|jsx|mjs|cjs|py|rs|go|java|kt|swift|rb|php|c|cc|cpp|h|hpp|cs|scala|sh|bash|zsh|yml|yaml|json|md|mdx|txt|toml|ini|css|scss|html|svelte|vue|astro|sql|graphql|prisma)$/i;
const MAX_FILE_BYTES = 200_000;

function walk(dir, base = dir, out = []) {
  for (const name of fs.readdirSync(dir)) {
    if (IGNORE_DIRS.has(name)) continue;
    const p = path.join(dir, name);
    const st = fs.statSync(p);
    if (st.isDirectory()) walk(p, base, out);
    else if (TEXT_EXT.test(name) && st.size <= MAX_FILE_BYTES) out.push({ path: path.relative(base, p).replaceAll("\\\\", "/"), size: st.size });
  }
  return out;
}

function sha1(s) { return crypto.createHash("sha1").update(s).digest("hex"); }

function chunkText(text, target = 3200 /* ~800 tokens */, overlap = 400) {
  const chunks = [];
  let i = 0;
  while (i < text.length) {
    const end = Math.min(text.length, i + target);
    chunks.push(text.slice(i, end));
    if (end === text.length) break;
    i = end - overlap;
  }
  return chunks;
}

function extractSymbols(text) {
  const out = [];
  const rx = /^\\s*export\\s+(?:async\\s+)?(?:function|class|const|let|var|interface|type|enum)\\s+([A-Za-z_$][\\w$]*)/gm;
  let m; while ((m = rx.exec(text)) && out.length < 40) out.push({ name: m[1], kind: "export", line: text.slice(0, m.index).split("\\n").length });
  return out;
}

async function embedBatch(mistralKey, inputs) {
  const res = await fetch("https://api.mistral.ai/v1/embeddings", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + mistralKey },
    body: JSON.stringify({ model: "mistral-embed", input: inputs }),
  });
  if (!res.ok) throw new Error("mistral embed " + res.status + " " + (await res.text()).slice(0, 300));
  const body = await res.json();
  return body.data.map((d) => d.embedding);
}

async function summarize(openrouterKey, model, filePath, snippet) {
  const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + openrouterKey },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: "You summarize source files in ONE sentence (max 40 words): purpose + key exports. No preamble." },
        { role: "user", content: "Path: " + filePath + "\\n\\n" + snippet.slice(0, 6000) },
      ],
      max_tokens: 100,
      temperature: 0.2,
    }),
  });
  if (!res.ok) return "";
  const body = await res.json();
  return (body.choices?.[0]?.message?.content ?? "").trim().slice(0, 300);
}

async function runIndex(spec) {
  const files = walk(process.cwd());
  await log("Indexing " + files.length + " files with mistral-embed…");
  await api("/api/public/jobs/index-progress", { current: 0, total: files.length });

  let done = 0;
  for (const f of files) {
    try {
      const content = fs.readFileSync(f.path, "utf8");
      const sha = sha1(content);
      const chunks = chunkText(content);
      // Batch embed (Mistral accepts up to ~ many inputs; keep to 32 per call)
      const embeddings = [];
      for (let i = 0; i < chunks.length; i += 32) {
        const slice = chunks.slice(i, i + 32);
        const embs = await embedBatch(spec.mistral_key, slice);
        embeddings.push(...embs);
      }
      const summary = await summarize(spec.openrouter_key, spec.model, f.path, content);
      const symbols = extractSymbols(content);
      await api("/api/public/jobs/index-batch", {
        file: { path: f.path, sha, size: f.size, language: (f.path.split(".").pop() || "").toLowerCase() || null, summary, symbols },
        chunks: chunks.map((c, i) => ({ chunk_index: i, content: c, embedding: embeddings[i], token_count: Math.round(c.length / 4) })),
      });
    } catch (e) {
      await log("skip " + f.path + ": " + (e.message ?? e).toString().slice(0, 200));
    }
    done++;
    if (done % 5 === 0 || done === files.length) {
      await api("/api/public/jobs/index-progress", { current: done, total: files.length });
      await log("indexed " + done + "/" + files.length);
    }
  }
  await api("/api/public/jobs/complete", { status: "completed", summary: "Indexed " + done + " files." });
}

main().catch(async (e) => { await log("FATAL " + (e.message ?? e)); try { await api("/api/public/jobs/complete", { status: "failed", error: String(e.message ?? e) }); } catch {} process.exit(1); });
`;