#!/usr/bin/env node
/* Auto-generated by Coderbot. Runs one coding job (or a continuation of one)
 * inside GitHub Actions. Everything is driven by the app over HTTP, so the job
 * keeps running even when the user closes their browser. */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const JOB_ID = process.env.JOB_ID;
const JOB_SECRET = process.env.JOB_SECRET;
const APP_URL = process.env.APP_URL;
const BRANCH = process.env.WORKING_BRANCH;
/* The branch the user will merge into, and the throwaway branch this task
 * pushes to. Nothing lands on BASE_BRANCH without the user approving it. */
let BASE_BRANCH = BRANCH;
let REVIEW_BRANCH = BRANCH;

if (!JOB_ID || !JOB_SECRET || !APP_URL) { console.error("missing env"); process.exit(1); }

const HEAD = { "Content-Type": "application/json", "X-Job-Id": JOB_ID, "X-Job-Secret": JOB_SECRET };
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function api(p, body) {
  let lastError;
  for (let attempt = 0; attempt < 6; attempt++) {
    try {
      const r = await fetch(APP_URL + p, { method: "POST", headers: HEAD, body: JSON.stringify(body ?? {}) });
      if (r.ok) return r.json();
      const text = await r.text();
      const error = new Error(p + " " + r.status + " " + text);
      if (r.status !== 429 && r.status < 500) throw error;
      lastError = error;
    } catch (e) {
      lastError = e;
      if (attempt === 5) break;
    }
    await delay(Math.min(30000, 1000 * (2 ** attempt)) + Math.floor(Math.random() * 500));
  }
  throw lastError || new Error(p + " failed after retries");
}

const log = async (line) => { console.log(line); try { await api("/api/public/jobs/log", { line }); } catch {} };

/* The activity feed the user sees in the app. */
let PHASE = "planning";
/* `agent` is { id, label } — omitted means the main agent. */
const event = async (kind, text, phase, agent) => {
  if (phase && !agent) PHASE = phase;
  try {
    await api("/api/public/jobs/event", {
      kind,
      text: String(text).slice(0, 3500),
      phase: phase || PHASE,
      agent_id: agent ? agent.id : "main",
      agent_label: agent ? agent.label : "Main agent",
    });
  } catch {}
};

const sh = (cmd, opts = {}) => execSync(cmd, { stdio: ["pipe", "pipe", "pipe"], encoding: "utf8", timeout: 1000 * 60 * 10, ...opts });

const MAX_STEPS = 200;
const START = Date.now();
const TIME_LIMIT_MS = 1000 * 60 * 60 * 5.2; // checkpoint well before the 6h wall

/* ---------------------------------- tools --------------------------------- */

const IGNORE_DIRS = new Set(["node_modules", ".git", "dist", "build", ".next", ".turbo", ".cache", "coverage", "out", ".venv", "venv", "target", ".output"]);
const TEXT_EXT = /\.(ts|tsx|js|jsx|mjs|cjs|py|rs|go|java|kt|swift|rb|php|c|cc|cpp|h|hpp|cs|scala|sh|bash|zsh|yml|yaml|json|md|mdx|txt|toml|ini|css|scss|html|svelte|vue|astro|sql|graphql|prisma)$/i;

function walk(dir, base = dir, out = []) {
  let names = [];
  try { names = fs.readdirSync(dir); } catch { return out; }
  for (const name of names) {
    if (IGNORE_DIRS.has(name)) continue;
    const p = path.join(dir, name);
    let st; try { st = fs.statSync(p); } catch { continue; }
    if (st.isDirectory()) walk(p, base, out);
    else if (TEXT_EXT.test(name) && st.size <= 200000) out.push({ path: path.relative(base, p).split(path.sep).join("/"), size: st.size });
  }
  return out;
}

function readFileSafe(p) { try { return fs.readFileSync(p, "utf8"); } catch { return null; } }
function writeFileSafe(p, content) { fs.mkdirSync(path.dirname(p) || ".", { recursive: true }); fs.writeFileSync(p, content, "utf8"); }

let TODOS = [];

const tools = [
  { type: "function", function: { name: "list_files", description: "List repository files. Optional substring filter on the path.",
    parameters: { type: "object", properties: { filter: { type: "string" } } } } },
  { type: "function", function: { name: "glob", description: "Find files by glob pattern (e.g. 'src/**/*.tsx', '**/*.test.ts'). Faster than list_files for targeted lookups.",
    parameters: { type: "object", properties: { pattern: { type: "string" }, max_results: { type: "number" } }, required: ["pattern"] } } },
  { type: "function", function: { name: "read_file", description: "Read a text file. Optionally read a slice with `offset` (1-based start line) and `limit` (line count). Output is line-numbered.",
    parameters: { type: "object", properties: { path: { type: "string" }, offset: { type: "number" }, limit: { type: "number" } }, required: ["path"] } } },
  { type: "function", function: { name: "read_files", description: "Read several files at once. Use this instead of many read_file calls when exploring.",
    parameters: { type: "object", properties: { paths: { type: "array", items: { type: "string" } } }, required: ["paths"] } } },
  { type: "function", function: { name: "search_code", description: "Search the repo for a regular expression. Returns path:line matches. Optional `path_filter` substring and `context` lines.",
    parameters: { type: "object", properties: { query: { type: "string" }, max_results: { type: "number" }, path_filter: { type: "string" }, context: { type: "number" } }, required: ["query"] } } },
  { type: "function", function: { name: "write_file", description: "Create or overwrite a file with the COMPLETE new contents.",
    parameters: { type: "object", properties: { path: { type: "string" }, content: { type: "string" } }, required: ["path", "content"] } } },
  { type: "function", function: { name: "edit_file", description: "Replace an exact substring in a file. Prefer this for small edits.",
    parameters: { type: "object", properties: { path: { type: "string" }, find: { type: "string" }, replace: { type: "string" }, replace_all: { type: "boolean" } }, required: ["path", "find", "replace"] } } },
  { type: "function", function: { name: "multi_edit", description: "Apply several find/replace edits, optionally across several files, in one atomic call. All edits must match or none are applied.",
    parameters: { type: "object", properties: { edits: { type: "array", items: { type: "object", properties: { path: { type: "string" }, find: { type: "string" }, replace: { type: "string" }, replace_all: { type: "boolean" } }, required: ["path", "find", "replace"] } } }, required: ["edits"] } } },
  { type: "function", function: { name: "delete_file", description: "Delete a file.",
    parameters: { type: "object", properties: { path: { type: "string" } }, required: ["path"] } } },
  { type: "function", function: { name: "move_file", description: "Rename or move a file, creating parent directories as needed.",
    parameters: { type: "object", properties: { from: { type: "string" }, to: { type: "string" } }, required: ["from", "to"] } } },
  { type: "function", function: { name: "run_shell", description: "Run a shell command from the repo root. Returns combined output (truncated). Optional timeout_seconds (default 300, max 900).",
    parameters: { type: "object", properties: { cmd: { type: "string" }, timeout_seconds: { type: "number" } }, required: ["cmd"] } } },
  { type: "function", function: { name: "git_diff", description: "Show the diff of your uncommitted work so far. Optional path to scope it.",
    parameters: { type: "object", properties: { path: { type: "string" } } } } },
  { type: "function", function: { name: "fetch_url", description: "Fetch a URL and return its text (HTML stripped, truncated). Use for docs and API references.",
    parameters: { type: "object", properties: { url: { type: "string" } }, required: ["url"] } } },
  { type: "function", function: { name: "check_code", description: "Verify your work: runs the project's typecheck/lint/test/build scripts when they exist, plus static checks on changed files. Call this after editing and fix anything it reports.",
    parameters: { type: "object", properties: {} } } },
  { type: "function", function: { name: "update_plan", description: "Record or update your task list so the user can follow along. Each item has a title and a status of pending, in_progress or done.",
    parameters: { type: "object", properties: { todos: { type: "array", items: { type: "object", properties: { title: { type: "string" }, status: { type: "string" } }, required: ["title", "status"] } } }, required: ["todos"] } } },
  { type: "function", function: { name: "finish", description: "Call only when the task is complete and check_code is clean. Provide a user-facing summary and a commit message.",
    parameters: { type: "object", properties: { summary: { type: "string" }, commit_message: { type: "string" } }, required: ["summary", "commit_message"] } } },
];

const DELEGATE_TOOL = { type: "function", function: {
  name: "delegate",
  description: "Hand a FULL workstream — not an errand — to one of your sub-agents. Split the overall task into roughly equal shares: one per sub-agent plus one for yourself. Issue every delegate call for a round in the SAME turn so the sub-agents run in parallel. Brief each one like a colleague who just walked in: it has not seen this conversation, so give the goal, the exact files it owns, what to change, and how to verify — never 'based on your findings, fix it'. Each assignment must be a paragraph or more. When they report back, immediately delegate the next comparable chunk if meaningful work remains. Never give two sub-agents the same file, and never invent a sub-agent's result — wait for it. Do NOT delegate a single read, grep or one-line edit; do those yourself.",
  parameters: { type: "object", properties: {
    agent_id: { type: "string" },
    task: { type: "string", description: "A complete workstream: the goal, every file it owns, what to implement or change, edge cases, and how to verify. Comparable in size to what you keep for yourself." },
    files: { type: "array", items: { type: "string" }, description: "Files this sub-agent owns. Used to stop two sub-agents editing the same file." },
  }, required: ["agent_id", "task"] },
} };

/* Read-only tools can safely run at the same time within one assistant turn. */
const READ_ONLY_TOOLS = new Set(["list_files", "glob", "read_file", "read_files", "search_code", "git_diff", "fetch_url"]);

/* Tools available to the model this step. `finish` and `delegate` are main-agent only. */
function toolsFor(kind, subAgents) {
  if (kind === "sub") return tools.filter((t) => t.function.name !== "finish");
  return subAgents && subAgents.length ? [...tools, DELEGATE_TOOL] : tools;
}

// Sub-agents reason in parallel, while checkout mutations and commands are
// serialized. This keeps their speed advantage without corrupting shared files
// or running builds against half-written code.
let mutationQueue = Promise.resolve();
function serialized(task) {
  const next = mutationQueue.then(task, task);
  mutationQueue = next.catch(() => {});
  return next;
}

/* A cheap orientation pass so the model doesn't burn steps discovering the
 * basics: project type, scripts, top-level layout and any agent instructions. */
function repoBriefing() {
  const parts = [];
  try {
    const top = fs.readdirSync(".", { withFileTypes: true })
      .filter((d) => !d.name.startsWith(".git") && d.name !== "node_modules")
      .map((d) => d.name + (d.isDirectory() ? "/" : ""))
      .slice(0, 80);
    parts.push("Top level: " + top.join(" "));
  } catch {}
  try {
    const pkg = JSON.parse(fs.readFileSync("package.json", "utf8"));
    parts.push("package.json name: " + (pkg.name || "?"));
    if (pkg.scripts) parts.push("Scripts: " + Object.keys(pkg.scripts).join(", "));
    const deps = Object.keys({ ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) });
    if (deps.length) parts.push("Dependencies: " + deps.slice(0, 60).join(", "));
    parts.push("node_modules is " + (fs.existsSync("node_modules") ? "present" : "NOT installed — run `npm install` (or the matching package manager) with run_shell before any build/test command"));
  } catch {}
  for (const f of ["AGENTS.md", "CLAUDE.md", "CONTRIBUTING.md"]) {
    try {
      if (fs.existsSync(f)) parts.push("--- " + f + " (follow these repo instructions) ---\n" + fs.readFileSync(f, "utf8").slice(0, 6000));
    } catch {}
  }
  return "Repository briefing (gathered automatically, no tool call needed):\n" + parts.join("\n");
}


function changedFiles() {
  try {
    return sh("git status --porcelain").split("\n").map((l) => l.slice(3).trim()).filter(Boolean);
  } catch { return []; }
}

function pkgScripts() {
  const raw = readFileSafe("package.json");
  if (!raw) return {};
  try { return JSON.parse(raw).scripts ?? {}; } catch { return {}; }
}

function runCheckCode() {
  const problems = [];
  const files = changedFiles().filter((f) => TEXT_EXT.test(f));

  for (const f of files) {
    const content = readFileSafe(f);
    if (content == null) continue;
    if (!content.trim()) { problems.push(f + ": file is empty"); continue; }
    if (/^<{7}|^>{7}|^={7}$/m.test(content)) problems.push(f + ": leftover merge conflict markers");
    for (const pair of [["{", "}", "braces"], ["(", ")", "parens"], ["[", "]", "brackets"]]) {
      const o = content.split(pair[0]).length - 1;
      const c = content.split(pair[1]).length - 1;
      if (o !== c) problems.push(f + ": unbalanced " + pair[2] + " (" + o + " vs " + c + ")");
    }
    const importRe = /(?:from|require\()\s*['"](\.[^'"]+)['"]/g;
    let m;
    while ((m = importRe.exec(content))) {
      const spec = m[1];
      const base = path.normalize(path.join(path.dirname(f), spec));
      const cands = ["", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".py", ".css", ".json", "/index.ts", "/index.tsx", "/index.js"].map((s) => base + s);
      if (!cands.some((c) => fs.existsSync(c))) problems.push(f + ": imports missing local file " + spec);
    }
  }

  const scripts = pkgScripts();
  const ran = [];
  const hasNodeModules = fs.existsSync("node_modules");
  const candidates = ["typecheck", "tsc", "lint", "test", "build"].filter((n) => scripts[n]);
  if (candidates.length && !hasNodeModules) {
    problems.push("Dependencies are not installed, so " + candidates.join("/") + " could not run. Run `npm ci || npm install` with run_shell first if you need real verification.");
  } else {
    for (const name of candidates) {
      // `build` is slow; only run it when nothing cheaper exists.
      if (name === "build" && ran.length) continue;
      ran.push(name);
      try { sh("npm run " + name + " --silent", { timeout: 1000 * 60 * 12 }); }
      catch (e) {
        const out = ((e.stdout || "") + (e.stderr || "")).toString().slice(-4000);
        problems.push("npm run " + name + " failed:\n" + out);
      }
    }
  }
  return { changed: files, ran, problems, clean: problems.length === 0 };
}

/* Simple glob → RegExp (supports **, *, ?). */
function globToRe(pattern) {
  let out = "";
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i];
    if (ch === "*") {
      if (pattern[i + 1] === "*") { out += ".*"; i++; if (pattern[i + 1] === "/") i++; }
      else out += "[^/]*";
    } else if (ch === "?") out += "[^/]";
    else out += ch.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  }
  return new RegExp("^" + out + "$");
}

function numbered(content, offset = 1) {
  return content.split("\n").map((l, i) => (i + offset) + "\t" + l).join("\n");
}

async function execTool(name, args) {
  try {
    if (name === "list_files") {
      let files = walk(process.cwd()).map((f) => f.path);
      if (args.filter) files = files.filter((f) => f.includes(args.filter));
      return files.slice(0, 800).join("\n") || "(no files)";
    }
    if (name === "glob") {
      const re = globToRe(String(args.pattern || "**"));
      const hits = walk(process.cwd()).map((f) => f.path).filter((p) => re.test(p));
      return hits.slice(0, Math.min(args.max_results || 300, 1000)).join("\n") || "(no matches)";
    }
    if (name === "read_file") {
      const c = readFileSafe(args.path);
      if (c == null) return "ERR: not found";
      if (args.offset || args.limit) {
        const start = Math.max(1, Math.floor(args.offset || 1));
        const lines = c.split("\n").slice(start - 1, start - 1 + Math.max(1, Math.floor(args.limit || 200)));
        return numbered(lines.join("\n"), start).slice(0, 60000);
      }
      return numbered(c).slice(0, 60000);
    }
    if (name === "read_files") {
      const paths = Array.isArray(args.paths) ? args.paths.slice(0, 20) : [];
      return paths.map((p) => {
        const c = readFileSafe(p);
        return "--- " + p + " ---\n" + (c == null ? "(not found)" : c.slice(0, 20000));
      }).join("\n\n").slice(0, 80000) || "ERR: no paths given";
    }
    if (name === "search_code") {
      let re; try { re = new RegExp(args.query, "i"); } catch (e) { return "ERR: bad pattern " + e.message; }
      const limit = Math.min(args.max_results || 60, 200);
      const ctx = Math.min(Math.max(args.context || 0, 0), 4);
      const hits = [];
      for (const f of walk(process.cwd())) {
        if (args.path_filter && !f.path.includes(args.path_filter)) continue;
        const c = readFileSafe(f.path);
        if (c == null) continue;
        const lines = c.split("\n");
        for (let i = 0; i < lines.length; i++) {
          if (re.test(lines[i])) {
            if (ctx) {
              const from = Math.max(0, i - ctx);
              const to = Math.min(lines.length, i + ctx + 1);
              hits.push(f.path + ":" + (i + 1) + "\n" + lines.slice(from, to).map((l, k) => (from + k + 1) + "\t" + l.slice(0, 200)).join("\n"));
            } else {
              hits.push(f.path + ":" + (i + 1) + ": " + lines[i].slice(0, 200).trim());
            }
            if (hits.length >= limit) break;
          }
        }
        if (hits.length >= limit) break;
      }
      return hits.join("\n").slice(0, 40000) || "(no matches)";
    }
    if (name === "write_file") { writeFileSafe(args.path, args.content ?? ""); return "OK wrote " + args.path; }
    if (name === "edit_file") {
      const c = readFileSafe(args.path);
      if (c == null) return "ERR: not found";
      if (!c.includes(args.find)) return "ERR: the `find` text does not appear in the file — read it again";
      const next = args.replace_all ? c.split(args.find).join(args.replace) : c.replace(args.find, args.replace);
      writeFileSafe(args.path, next);
      return "OK edited " + args.path;
    }
    if (name === "multi_edit") {
      const edits = Array.isArray(args.edits) ? args.edits : [];
      if (!edits.length) return "ERR: no edits given";
      const staged = new Map();
      for (const e of edits) {
        const current = staged.has(e.path) ? staged.get(e.path) : readFileSafe(e.path);
        if (current == null) return "ERR: not found: " + e.path + " (no edits applied)";
        if (!current.includes(e.find)) return "ERR: `find` text not present in " + e.path + " (no edits applied) — read the file again";
        staged.set(e.path, e.replace_all ? current.split(e.find).join(e.replace) : current.replace(e.find, e.replace));
      }
      for (const [p, content] of staged) writeFileSafe(p, content);
      return "OK applied " + edits.length + " edits to " + [...staged.keys()].join(", ");
    }
    if (name === "delete_file") { fs.unlinkSync(args.path); return "OK deleted " + args.path; }
    if (name === "move_file") {
      const c = readFileSafe(args.from);
      if (c == null) return "ERR: not found: " + args.from;
      writeFileSafe(args.to, c);
      fs.unlinkSync(args.from);
      return "OK moved " + args.from + " → " + args.to;
    }
    if (name === "run_shell") {
      const secs = Math.min(Math.max(Math.floor(args.timeout_seconds || 300), 1), 900);
      return sh(args.cmd, { timeout: secs * 1000 }).slice(0, 12000) || "(no output)";
    }
    if (name === "git_diff") {
      const out = sh("git --no-pager diff -- " + (args.path ? JSON.stringify(args.path) : "."));
      const untracked = sh("git ls-files --others --exclude-standard").trim();
      return ((out || "(no tracked changes)") + (untracked ? "\n\nUntracked files:\n" + untracked : "")).slice(0, 30000);
    }
    if (name === "fetch_url") {
      const res = await fetch(String(args.url), { headers: { "User-Agent": "coderbot-runner" } });
      const text = await res.text();
      const clean = text
        .replace(/<script[\s\S]*?<\/script>/gi, "")
        .replace(/<style[\s\S]*?<\/style>/gi, "")
        .replace(/<[^>]+>/g, " ")
        .replace(/\s{2,}/g, " ");
      return ("HTTP " + res.status + "\n" + clean).slice(0, 20000);
    }
    if (name === "check_code") { return JSON.stringify(runCheckCode()).slice(0, 12000); }
    if (name === "update_plan") { TODOS = Array.isArray(args.todos) ? args.todos : []; return "OK"; }
    return "ERR: unknown tool";
  } catch (e) {
    return "ERR: " + ((e && (e.stderr || e.stdout) ? (e.stderr || e.stdout).toString() : (e && e.message) || String(e))).slice(0, 4000);
  }
}

/* --------------------------- provider / model call ------------------------- */

function chatRoute(spec, model) {
  if (model.startsWith("mistral:")) return { base: "https://api.mistral.ai/v1", key: spec.mistral_key, model: model.slice(8) };
  if (model.startsWith("groq:")) return { base: "https://api.groq.com/openai/v1", key: spec.groq_key, model: model.slice(5) };
  if (model.startsWith("nvidia:")) return { base: "https://integrate.api.nvidia.com/v1", key: spec.nvidia_key, model: model.slice(7) };
  return { base: "https://openrouter.ai/api/v1", key: spec.openrouter_key, model };
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/* Per-minute rate limits: wait 10s and retry (up to ~50 minutes of waiting).
 * Transient network/5xx failures back off and retry a few times.
 * Any other limit (quota / credits / context) stops the run with the
 * provider's message. */
async function callModel(spec, messages, opts = {}) {
  const route = chatRoute(spec, opts.model || spec.model);
  const activeTools = opts.tools || toolsFor("main", spec.sub_agents);
  let rpmWaits = 0;
  let transient = 0;
  for (;;) {
    let res;
    try {
      res = await fetch(route.base + "/chat/completions", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: "Bearer " + route.key },
        body: JSON.stringify(activeTools && activeTools.length
          ? { model: route.model, messages, tools: activeTools, tool_choice: "auto" }
          : { model: route.model, messages }),
      });
    } catch (e) {
      if (++transient > 6) throw new Error("Network error talking to the model provider: " + ((e && e.message) || e));
      await sleep(Math.min(30000, 2000 * transient));
      continue;
    }
    if (res.ok) {
      const body = await res.json().catch(() => null);
      if (body && body.choices && body.choices.length) return body;
      if (body && body.error) throw new Error("Provider error: " + JSON.stringify(body.error).slice(0, 600));
      if (++transient > 6) throw new Error("The model returned an empty response repeatedly.");
      await sleep(2000 * transient);
      continue;
    }
    const text = (await res.text()).slice(0, 800);
    const isRpm = res.status === 429 && (/per.?minute|rpm|requests per|rate.?limit/i.test(text) || !/quota|credit|balance|billing/i.test(text));
    if (isRpm) {
      if (++rpmWaits <= 300) {
        if (rpmWaits === 1 || rpmWaits % 6 === 0) {
          await event("status", "Rate limited — waiting and retrying (" + rpmWaits * 10 + "s so far).", undefined, opts.agent);
        }
        await sleep(10000);
        continue;
      }
      throw new Error("Still rate limited after 50 minutes of retrying. Stopping — try again later or use a model with a higher rate limit.");
    }
    if (res.status >= 500 || res.status === 408) {
      if (++transient > 6) throw new Error("Provider error " + res.status + ": " + text);
      await sleep(Math.min(30000, 2000 * transient));
      continue;
    }
    throw new Error("Provider error " + res.status + ": " + text);
  }
}

/* --------------------------- context management --------------------------- */

const approxTokens = (messages) => Math.round(JSON.stringify(messages).length / 4);
const COMPACT_AT_TOKENS = 90000;

/* Claude-Code-style compaction: when the transcript gets long, fold the older
 * middle of the conversation into a summary so the run can keep going without
 * blowing the model's context window. */
async function compactIfNeeded(spec, messages, agent) {
  if (approxTokens(messages) < COMPACT_AT_TOKENS) return messages;
  // Keep the system prompt, the first user turn, and the most recent exchanges.
  const head = messages.slice(0, 2);
  const keepTail = 12;
  const middle = messages.slice(2, Math.max(2, messages.length - keepTail));
  let tail = messages.slice(Math.max(2, messages.length - keepTail));
  // A tool message must follow its assistant tool_calls message; drop orphans.
  while (tail.length && tail[0].role === "tool") tail = tail.slice(1);
  if (middle.length < 4) return messages;

  await event("status", "Context is getting long — summarising earlier work to keep going.", undefined, agent);
  const transcript = middle.map((m) => {
    const calls = (m.tool_calls || []).map((c) => c.function.name + "(" + String(c.function.arguments || "").slice(0, 200) + ")").join(", ");
    return m.role + ": " + String(typeof m.content === "string" ? m.content : "").slice(0, 1200) + (calls ? " [tools: " + calls + "]" : "");
  }).join("\n").slice(0, 120000);

  let summary = "";
  try {
    const body = await callModel(spec, [
      { role: "system", content: "You compress an autonomous coding agent's transcript. Output a dense hand-off note: the goal, what was discovered about the codebase (files, symbols, decisions), every file already changed and how, what verification was run and its result, and what remains. No preamble." },
      { role: "user", content: transcript },
    ], { model: opts_model(spec, agent), tools: [], agent });
    summary = (body.choices[0].message.content || "").trim();
  } catch (e) {
    await log("compaction failed: " + ((e && e.message) || e));
    return messages;
  }
  if (!summary) return messages;
  return [
    ...head,
    { role: "user", content: "[Earlier work in this run, compacted]\n" + summary + "\n\nContinue from here." },
    ...tail,
  ];
}

function opts_model(spec, agent) {
  return agent && agent.model ? agent.model : spec.model;
}


/* Providers such as Groq reject assistant messages that carry extra fields
 * (e.g. `reasoning`, `executed_tools`) back on the next request, so only echo
 * the fields the chat-completions API defines. */
function sanitizeAssistant(msg) {
  const out = { role: "assistant", content: typeof msg.content === "string" ? msg.content : "" };
  if (Array.isArray(msg.tool_calls) && msg.tool_calls.length) {
    out.tool_calls = msg.tool_calls.map((c) => ({
      id: c.id,
      type: "function",
      function: { name: c.function && c.function.name, arguments: (c.function && c.function.arguments) || "{}" },
    }));
  }
  return out;
}

/* Keep the transcript small enough to carry across a checkpoint. */
function trimForCheckpoint(messages) {
  const out = messages.map((m) => (m.role === "tool" && typeof m.content === "string" && m.content.length > 4000
    ? { ...m, content: m.content.slice(0, 4000) + "\n…(truncated)" }
    : m));
  while (JSON.stringify(out).length > 400000 && out.length > 4) out.splice(1, 1);
  return out;
}

function verb(name, args) {
  if (name === "read_file") return "Read " + args.path;
  if (name === "read_files") return "Read " + (args.paths || []).join(", ").slice(0, 120);
  if (name === "list_files") return "Listed the repository files";
  if (name === "glob") return "Looked for files matching " + args.pattern;
  if (name === "search_code") return 'Searched for "' + String(args.query || "").slice(0, 60) + '"';
  if (name === "write_file") return "Wrote " + args.path;
  if (name === "edit_file") return "Edited " + args.path;
  if (name === "multi_edit") return "Edited " + [...new Set((args.edits || []).map((e) => e.path))].join(", ").slice(0, 140);
  if (name === "delete_file") return "Deleted " + args.path;
  if (name === "move_file") return "Moved " + args.from + " → " + args.to;
  if (name === "run_shell") return "Ran " + String(args.cmd || "").slice(0, 90);
  if (name === "git_diff") return "Reviewed my diff so far";
  if (name === "fetch_url") return "Fetched " + String(args.url || "").slice(0, 80);
  if (name === "check_code") return "Checked the code I changed for problems";
  if (name === "update_plan") return "Updated the plan: " + (args.todos || []).map((t) => t.title).join(" · ").slice(0, 200);
  if (name === "delegate") return "Delegated to " + (args.agent_id || "a sub-agent");
  return name;
}

const WRITE_TOOLS = new Set(["write_file", "edit_file", "multi_edit", "delete_file", "move_file"]);

/* Files each sub-agent has been given, so two agents never edit the same file. */
const FILE_OWNER = new Map();
function claimFiles(agentId, files) {
  const clashes = [];
  for (const f of files || []) {
    const owner = FILE_OWNER.get(f);
    if (owner && owner !== agentId) clashes.push(f + " (already owned by " + owner + ")");
    else FILE_OWNER.set(f, agentId);
  }
  return clashes;
}
function releaseFiles(agentId) {
  for (const [f, owner] of [...FILE_OWNER]) if (owner === agentId) FILE_OWNER.delete(f);
}

function phaseFor(name, sawCheck) {
  if (name === "write_file" || name === "edit_file" || name === "delete_file") return sawCheck ? "debugging" : "coding";
  if (name === "check_code") return "checking";
  if (name === "run_shell") return sawCheck ? "debugging" : "coding";
  return PHASE;
}

/* ----------------------------------- main --------------------------------- */

/* Pull the user's uploaded files into the checkout so code can use them. */
async function fetchAttachments(spec) {
  const list = spec.attachments || [];
  if (!list.length) return [];
  const readable = [];
  fs.mkdirSync("uploads", { recursive: true });
  for (const a of list) {
    const safe = String(a.name).replace(/[^\w.\-]+/g, "_");
    try {
      const res = await fetch(a.url);
      if (!res.ok) throw new Error("download " + res.status);
      const buf = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(path.join("uploads", safe), buf);
      await event("action", "Saved upload uploads/" + safe, PHASE);
      if (!a.code_only) readable.push({ name: safe, mime: a.mime_type || "", buf });
    } catch (e) {
      await log("attachment failed " + safe + ": " + ((e && e.message) || e));
    }
  }
  return readable;
}

/* Text/image content for the uploads the AI is allowed to read. */
function attachmentMessages(readable) {
  const out = [];
  const textParts = [];
  const imageParts = [];
  for (const a of readable) {
    if (/^image\//.test(a.mime)) {
      imageParts.push({ type: "image_url", image_url: { url: "data:" + a.mime + ";base64," + a.buf.toString("base64") } });
    } else {
      textParts.push("--- uploads/" + a.name + " ---\n" + a.buf.toString("utf8").slice(0, 40000));
    }
  }
  if (textParts.length) {
    out.push({ role: "user", content: "Files the user uploaded (also saved under uploads/):\n\n" + textParts.join("\n\n") });
  }
  if (imageParts.length) {
    out.push({ role: "user", content: [{ type: "text", text: "Images the user uploaded (also saved under uploads/)." }, ...imageParts] });
  }
  return out;
}

/* A sub-agent: same tools, same checkout, its own model and activity feed. */
async function runSubAgent(spec, agent, task, ownFiles) {
  const scopedAgent = { ...agent, ownFiles: Array.isArray(ownFiles) ? ownFiles : [] };
  const subTools = toolsFor("sub", spec.sub_agents);
  let messages = [
    { role: "system", content:
      "You are " + agent.label + ", a sub-agent of Coderbot working inside GitHub Actions on the repository checkout at " +
      (spec.repo ? spec.repo.owner + "/" + spec.repo.name : "this repo") + ". " +
      "Do only the part of the task you were given — do not touch unrelated files, do not commit, do not delegate. " +
      (ownFiles && ownFiles.length ? "You own these files; do not edit any others: " + ownFiles.join(", ") + ". " : "") +
      "Other sub-agents may be working on other files in this same checkout at the same time, so never reformat or rewrite files outside your scope. " +
      (agent.instructions ? "Your standing scope: " + agent.instructions + ". " : "") +
      "Work efficiently: batch reads with read_files, use search_code/glob to locate things, prefer edit_file or multi_edit over rewriting whole files. " +
      "Verify with check_code (or a targeted run_shell command) and fix what it reports. " +
      "When your part is done, reply with a plain-text report of exactly which files you changed and how (no tool call)." },
    { role: "user", content: task },
  ];
  await event("status", "Started on: " + String(task).slice(0, 160), "coding", agent);
  for (let step = 0; step < 80; step++) {
    messages = await compactIfNeeded(spec, messages, agent);
    const body = await callModel(spec, messages, { model: agent.model, tools: subTools, agent: scopedAgent });
    const msg = body.choices && body.choices[0] && body.choices[0].message;
    if (!msg) return "Sub-agent " + agent.id + " returned no message.";
    messages.push(sanitizeAssistant(msg));
    if (msg.content && String(msg.content).trim()) await event("thought", String(msg.content).trim().slice(0, 800), undefined, scopedAgent);
    const calls = msg.tool_calls || [];
    if (!calls.length) {
      await event("status", "Finished its part.", "done", agent);
      return String(msg.content || "Done.").slice(0, 6000);
    }
    const results = await runToolCalls(calls, scopedAgent, () => {});
    for (const c of calls) messages.push({ role: "tool", tool_call_id: c.id, content: results.get(c.id) });
  }
  await event("status", "Hit its step limit.", "done", agent);
  return "Sub-agent " + agent.id + " hit its step limit; check its work.";
}

/* Execute one assistant turn's tool calls. Read-only calls run concurrently,
 * writes and shell commands run in order so they can't race each other. */
async function runToolCalls(calls, agent, onTool) {
  const results = new Map();
  const parse = (c) => { try { return JSON.parse((c.function && c.function.arguments) || "{}"); } catch { return {}; } };

  const reads = calls.filter((c) => READ_ONLY_TOOLS.has(c.function.name));
  const rest = calls.filter((c) => !READ_ONLY_TOOLS.has(c.function.name));

  await Promise.all(reads.map(async (c) => {
    const args = parse(c);
    await event("action", verb(c.function.name, args), undefined, agent);
    onTool(c.function.name, args);
    results.set(c.id, String(await execTool(c.function.name, args)).slice(0, 40000));
  }));

  for (const c of rest) {
    const args = parse(c);
    const name = c.function.name;
    if (name === "delegate") { results.set(c.id, "ERR: sub-agents cannot delegate"); continue; }
    if (agent && WRITE_TOOLS.has(name) && agent.ownFiles && agent.ownFiles.length) {
      const requested = name === "multi_edit" ? (args.edits || []).map((e) => e.path)
        : name === "move_file" ? [args.from, args.to]
        : [args.path];
      const outside = requested.filter((p) => p && !agent.ownFiles.includes(p));
      if (outside.length) {
        results.set(c.id, "ERR: outside your assigned files: " + outside.join(", "));
        continue;
      }
    }
    await event("action", verb(name, args), undefined, agent);
    onTool(name, args);
    const run = () => execTool(name, args);
    const output = WRITE_TOOLS.has(name) || name === "run_shell" || name === "check_code"
      ? await serialized(run)
      : await run();
    results.set(c.id, String(output).slice(0, 40000));
  }
  return results;
}

async function main() {
  await log("Claiming job " + JOB_ID);
  const spec = await api("/api/public/jobs/claim");
  await log("Model: " + spec.model + " · mode: " + (spec.mode || "build"));

  BASE_BRANCH = spec.working_branch || BRANCH;
  REVIEW_BRANCH = "coderbot/task-" + String(spec.task_id || JOB_ID).slice(0, 40);

  if (spec.job_type === "index") { await runIndex(spec); return; }

  const resumed = spec.checkpoint && Array.isArray(spec.checkpoint.messages) && spec.checkpoint.messages.length > 0;
  const readable = resumed ? [] : await fetchAttachments(spec);
  let messages = resumed
    ? spec.checkpoint.messages
    : [{ role: "system", content: spec.system }, ...attachmentMessages(readable), ...spec.messages];
  const subAgents = spec.sub_agents || [];
  if (resumed) {
    TODOS = spec.checkpoint.todos || [];
    messages.push({ role: "user", content: "The previous run hit the GitHub Actions time limit and was checkpointed. Your uncommitted work was pushed to the branch and is present in this checkout. Continue where you left off until the task is complete." });
    await event("status", "Resumed after checkpoint — continuing the task.", "coding");
  } else {
    messages.splice(1, 0, { role: "user", content: repoBriefing() });
    await event("status", "Runner started on GitHub Actions in " + (spec.mode || "build") + " mode.", "planning");
    await event("thought", "Working out what this task needs and which files matter.", "planning");
  }

  let done = null;
  let sawCheck = false;
  let sawWrite = false;
  let noProgress = 0;
  let redelegateNote = null;

  for (let step = 0; step < MAX_STEPS; step++) {
    if (Date.now() - START > TIME_LIMIT_MS) {
      await checkpointAndContinue(messages);
      return;
    }
    messages = await compactIfNeeded(spec, messages);
    const body = await callModel(spec, messages);
    const msg = body.choices && body.choices[0] && body.choices[0].message;
    if (!msg) throw new Error("The model returned no message");
    messages.push(sanitizeAssistant(msg));

    if (msg.content && String(msg.content).trim()) {
      await event("thought", String(msg.content).trim().slice(0, 800));
    }

    const calls = msg.tool_calls || [];
    if (calls.length === 0) {
      // The model stopped calling tools. If it never verified its edits, nudge
      // it once instead of silently finishing on unchecked work.
      if (sawWrite && !sawCheck && noProgress === 0) {
        noProgress++;
        messages.push({ role: "user", content: "You changed files but never ran check_code. Run it now, fix anything it reports, then call finish." });
        continue;
      }
      done = { summary: msg.content || "Done.", commit_message: "Coderbot update" };
      break;
    }

    const parse = (c) => { try { return JSON.parse((c.function && c.function.arguments) || "{}"); } catch { return {}; } };

    // Sub-agents delegated in the same turn run concurrently, so several
    // models work on their parts at once instead of queueing behind each other.
    const delegateCalls = calls.filter((c) => c.function && c.function.name === "delegate");
    const delegateResults = new Map();
    if (delegateCalls.length) {
      await Promise.all(delegateCalls.map(async (c) => {
        const args = parse(c);
        const agent = subAgents.find((a) => a.id === args.agent_id);
        if (!agent) {
          delegateResults.set(c.id, "ERR: unknown agent_id " + String(args.agent_id || "") + ". Valid ids: " + subAgents.map((a) => a.id).join(", "));
          return;
        }
        const task = String(args.task || "").trim();
        // A one-line errand wastes a whole agent: make the split substantial.
        if (task.length < 120) {
          delegateResults.set(c.id, "ERR: that assignment is too small for a sub-agent. Give it a full workstream of comparable size to your own share — the goal, every file it owns, the behaviour to implement, and how to verify — in at least a short paragraph. Re-issue the delegate call with the bigger chunk.");
          return;
        }
        const clashes = claimFiles(agent.id, args.files);
        if (clashes.length) {
          delegateResults.set(c.id, "ERR: these files are already assigned to another sub-agent: " + clashes.join(", ") + ". Re-split the work so each agent owns different files.");
          return;
        }
        await event("action", "Delegated to " + agent.label + ": " + task.slice(0, 120), "coding");
        try {
          const report = await runSubAgent(spec, agent, task, args.files);
          delegateResults.set(c.id, (agent.label + " reported:\n" + report).slice(0, 20000));
        } catch (e) {
          const report = "Sub-agent failed: " + ((e && e.message) || e);
          await event("error", report, PHASE, agent);
          delegateResults.set(c.id, (agent.label + " reported:\n" + report).slice(0, 20000));
        } finally {
          releaseFiles(agent.id);
        }
      }));
      sawWrite = true;
      sawCheck = false; // sub-agent work must be verified by the main agent
      const idle = subAgents.map((a) => a.id + " (" + a.label + ")").join(", ");
      const pending = TODOS.filter((t) => t.status !== "done").map((t) => t.title).join("; ");
      redelegateNote = "All sub-agents are idle again: " + idle + ". "
        + (pending ? "Still open on your plan: " + pending + ". " : "")
        + "If any meaningful work remains, hand each idle sub-agent another comparable-sized chunk in your NEXT turn (several delegate calls at once) and take an equal share yourself. Only stop delegating when what is left is small enough that splitting it would cost more than doing it.";
    }


    // finish is handled inline; everything else goes through the shared executor.
    const finishCall = calls.find((c) => c.function.name === "finish");
    const others = calls.filter((c) => c.function.name !== "finish" && c.function.name !== "delegate");

    const results = others.length
      ? await runToolCalls(others, undefined, (name, args) => {
          if (WRITE_TOOLS.has(name)) sawWrite = true;
          if (name === "check_code") sawCheck = true;
          PHASE = phaseFor(name, sawCheck);
        })
      : new Map();

    for (const c of calls) {
      const name = c.function.name;
      if (name === "finish") continue;
      if (name === "delegate") {
        messages.push({ role: "tool", tool_call_id: c.id, content: delegateResults.get(c.id) ?? "ERR: delegation did not run" });
        continue;
      }
      const out = results.get(c.id) ?? "ERR: tool did not run";
      if (name === "check_code") {
        const clean = out.includes('"clean":true');
        await event("status", clean ? "Checks are clean." : "Found problems — fixing them.", clean ? "checking" : "debugging");
      }
      await log("→ " + name);
      messages.push({ role: "tool", tool_call_id: c.id, content: out });
    }

    if (redelegateNote) {
      messages.push({ role: "user", content: redelegateNote });
      redelegateNote = null;
    }



    if (finishCall) {
      const args = parse(finishCall);
      if (sawWrite && !sawCheck) {
        sawCheck = true;
        await event("action", "Checked the code I changed for problems", "checking");
        const result = runCheckCode();
        messages.push({ role: "tool", tool_call_id: finishCall.id, content: "Before finishing, verification ran automatically: " + JSON.stringify(result).slice(0, 8000) + (result.clean ? "\nClean — you may call finish again." : "\nFix these problems, then call check_code again.") });
        if (!result.clean) await event("status", "Found problems — fixing them.", "debugging");
        continue;
      }
      done = { summary: args.summary, commit_message: args.commit_message };
      messages.push({ role: "tool", tool_call_id: finishCall.id, content: "ok" });
      break;
    }
  }


  if (!done) {
    await checkpointAndContinue(messages);
    return;
  }

  await commitAndComplete(done);
}

async function gitCommit(message, branch) {
  sh("git config user.email 'coderbot@users.noreply.github.com'");
  sh("git config user.name 'Coderbot'");
  const status = sh("git status --porcelain");
  if (!status.trim()) return null;
  sh("git add -A");
  sh("git commit -m " + JSON.stringify(message));
  sh("git push --force origin HEAD:" + branch);
  return sh("git rev-parse HEAD").trim();
}

/* What the run changed, relative to the branch the user will merge into. */
function reviewDetails() {
  let files = [];
  let patch = "";
  try {
    sh("git fetch origin " + BASE_BRANCH + " --depth=200 || true");
    const range = "origin/" + BASE_BRANCH + "...HEAD";
    files = sh("git diff --name-status " + range).split("\n").map((l) => l.trim()).filter(Boolean)
      .map((l) => {
        const [status, ...rest] = l.split(/\s+/);
        return { status: status[0] === "A" ? "added" : status[0] === "D" ? "deleted" : status[0] === "R" ? "renamed" : "modified", path: rest.join(" ") };
      }).slice(0, 500);
    patch = sh("git --no-pager diff " + range).slice(0, 400000);
  } catch (e) {
    log("diff summary failed: " + ((e && e.message) || e));
  }
  return { files, patch };
}

/* The agent never lands work by itself: it pushes to a review branch and the
 * user approves the merge from the app. */
async function commitAndComplete(done) {
  try {
    const sha = await gitCommit(done.commit_message || "Coderbot update", REVIEW_BRANCH);
    if (sha) {
      const { files, patch } = reviewDetails();
      await event("status", "Pushed " + files.length + " changed file(s) to " + REVIEW_BRANCH + " — waiting for your approval.", "done");
      await api("/api/public/jobs/complete", {
        status: "awaiting_review",
        summary: done.summary || "Done.",
        commit_sha: sha,
        review_branch: REVIEW_BRANCH,
        base_branch: BASE_BRANCH,
        changed_files: files,
        diff: patch,
      });
    } else {
      await event("status", "Finished — no file changes were needed.", "done");
      await api("/api/public/jobs/complete", { status: "completed", summary: done.summary || "No changes." });
    }
  } catch (e) {
    await event("error", "Push failed: " + ((e && e.message) || e), "done");
    await api("/api/public/jobs/complete", { status: "failed", error: String((e && e.message) || e) });
    process.exit(1);
  }
}

/* Save state, push work in progress, and ask the app to dispatch a follow-up
 * run so long tasks survive the 6h GitHub Actions limit. */
async function checkpointAndContinue(messages) {
  await event("status", "Approaching the GitHub Actions time limit — saving progress and starting a fresh run.", PHASE);
  try { await gitCommit("Coderbot checkpoint (work in progress)", REVIEW_BRANCH); } catch (e) { await log("checkpoint push failed: " + ((e && e.message) || e)); }
  const checkpoint = { messages: trimForCheckpoint(messages), todos: TODOS };
  await api("/api/public/jobs/checkpoint", { checkpoint });
  const res = await api("/api/public/jobs/continue", { checkpoint, review_branch: REVIEW_BRANCH });
  await event("status", "Continuing in a new GitHub Actions run.", PHASE);
  await log("continuation job " + (res.job_id || "?"));
}


/* ============================ Indexing mode ============================ */

function sha1(s) { return crypto.createHash("sha1").update(s).digest("hex"); }

function chunkText(text, target = 3200, overlap = 400) {
  const chunks = [];
  let i = 0;
  while (i < text.length) {
    const end = Math.min(text.length, i + target);
    chunks.push(text.slice(i, end));
    if (end === text.length) break;
    i = end - overlap;
  }
  return chunks;
}

function extractSymbols(text) {
  const out = [];
  const rx = /^\s*export\s+(?:async\s+)?(?:function|class|const|let|var|interface|type|enum)\s+([A-Za-z_$][\w$]*)/gm;
  let m;
  while ((m = rx.exec(text)) && out.length < 40) out.push({ name: m[1], kind: "export", line: text.slice(0, m.index).split("\n").length });
  return out;
}

async function embedBatch(spec, inputs) {
  const base = spec.embedding_provider === "mistral" ? "https://api.mistral.ai/v1"
    : spec.embedding_provider === "nvidia" ? "https://integrate.api.nvidia.com/v1"
    : "https://openrouter.ai/api/v1";
  for (let attempt = 0; ; attempt++) {
    const res = await fetch(base + "/embeddings", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: "Bearer " + spec.embedding_key },
      body: JSON.stringify({ model: spec.embedding_model, input: inputs }),
    });
    if (res.ok) { const body = await res.json(); return body.data.map((d) => d.embedding); }
    const text = (await res.text()).slice(0, 300);
    if (res.status === 429 && attempt < 300) { await sleep(10000); continue; }
    throw new Error(spec.embedding_provider + " embed " + res.status + " " + text);
  }
}

async function summarize(spec, filePath, snippet) {
  const route = chatRoute(spec, spec.model);
  const res = await fetch(route.base + "/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + route.key },
    body: JSON.stringify({
      model: route.model,
      messages: [
        { role: "system", content: "You summarize source files in ONE sentence (max 40 words): purpose + key exports. No preamble." },
        { role: "user", content: "Path: " + filePath + "\n\n" + snippet.slice(0, 6000) },
      ],
      max_tokens: 100,
      temperature: 0.2,
    }),
  });
  if (!res.ok) return "";
  const body = await res.json();
  return ((body.choices && body.choices[0] && body.choices[0].message.content) || "").trim().slice(0, 300);
}

async function runIndex(spec) {
  const files = walk(process.cwd());
  await log("Indexing " + files.length + " files with " + spec.embedding_model + "…");
  await api("/api/public/jobs/index-progress", { current: 0, total: files.length });
  let done = 0;
  for (const f of files) {
    try {
      const content = fs.readFileSync(f.path, "utf8");
      const sha = sha1(content);
      const chunks = chunkText(content);
      const embeddings = [];
      for (let i = 0; i < chunks.length; i += 32) embeddings.push(...(await embedBatch(spec, chunks.slice(i, i + 32))));
      const summary = await summarize(spec, f.path, content);
      await api("/api/public/jobs/index-batch", {
        file: { path: f.path, sha, size: f.size, language: (f.path.split(".").pop() || "").toLowerCase() || null, summary, symbols: extractSymbols(content) },
        chunks: chunks.map((c, i) => ({ chunk_index: i, content: c, embedding: embeddings[i], token_count: Math.round(c.length / 4) })),
      });
    } catch (e) {
      await log("skip " + f.path + ": " + String((e && e.message) || e).slice(0, 200));
    }
    done++;
    if (done % 5 === 0 || done === files.length) {
      await api("/api/public/jobs/index-progress", { current: done, total: files.length });
      await log("indexed " + done + "/" + files.length);
    }
  }
  await api("/api/public/jobs/complete", { status: "completed", summary: "Indexed " + done + " files." });
}

main().catch(async (e) => {
  const msg = String((e && e.message) || e);
  await log("FATAL " + msg);
  try { await event("error", msg, PHASE); } catch {}
  try { await api("/api/public/jobs/complete", { status: "failed", error: msg }); } catch {}
  process.exit(1);
});
