/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as ApiGithubCallbackRouteImport } from './routes/api/github.callback'
import { Route as ApiPublicJobsCheckpointRouteImport } from './routes/api/public/jobs/checkpoint'
import { Route as ApiPublicJobsClaimRouteImport } from './routes/api/public/jobs/claim'
import { Route as ApiPublicJobsCompleteRouteImport } from './routes/api/public/jobs/complete'
import { Route as ApiPublicJobsContinueRouteImport } from './routes/api/public/jobs/continue'
import { Route as ApiPublicJobsEventRouteImport } from './routes/api/public/jobs/event'
import { Route as ApiPublicJobsIndexBatchRouteImport } from './routes/api/public/jobs/index-batch'
import { Route as ApiPublicJobsIndexProgressRouteImport } from './routes/api/public/jobs/index-progress'
import { Route as ApiPublicJobsKaggleRouteImport } from './routes/api/public/jobs/kaggle'
import { Route as ApiPublicJobsLogRouteImport } from './routes/api/public/jobs/log'
import { Route as ApiPublicJobsNewMessagesRouteImport } from './routes/api/public/jobs/new-messages'
import { Route as ApiPublicJobsReferenceRouteImport } from './routes/api/public/jobs/reference'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const ApiGithubCallbackRoute = ApiGithubCallbackRouteImport.update({
  id: '/api/github/callback',
  path: '/api/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsCheckpointRoute = ApiPublicJobsCheckpointRouteImport.update({
  id: '/api/public/jobs/checkpoint',
  path: '/api/public/jobs/checkpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsClaimRoute = ApiPublicJobsClaimRouteImport.update({
  id: '/api/public/jobs/claim',
  path: '/api/public/jobs/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsCompleteRoute = ApiPublicJobsCompleteRouteImport.update({
  id: '/api/public/jobs/complete',
  path: '/api/public/jobs/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsContinueRoute = ApiPublicJobsContinueRouteImport.update({
  id: '/api/public/jobs/continue',
  path: '/api/public/jobs/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsEventRoute = ApiPublicJobsEventRouteImport.update({
  id: '/api/public/jobs/event',
  path: '/api/public/jobs/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsIndexBatchRoute = ApiPublicJobsIndexBatchRouteImport.update({
  id: '/api/public/jobs/index-batch',
  path: '/api/public/jobs/index-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsIndexProgressRoute =
  ApiPublicJobsIndexProgressRouteImport.update({
    id: '/api/public/jobs/index-progress',
    path: '/api/public/jobs/index-progress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsKaggleRoute = ApiPublicJobsKaggleRouteImport.update({
  id: '/api/public/jobs/kaggle',
  path: '/api/public/jobs/kaggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsLogRoute = ApiPublicJobsLogRouteImport.update({
  id: '/api/public/jobs/log',
  path: '/api/public/jobs/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsNewMessagesRoute =
  ApiPublicJobsNewMessagesRouteImport.update({
    id: '/api/public/jobs/new-messages',
    path: '/api/public/jobs/new-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJobsReferenceRoute = ApiPublicJobsReferenceRouteImport.update({
  id: '/api/public/jobs/reference',
  path: '/api/public/jobs/reference',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/jobs/checkpoint': typeof ApiPublicJobsCheckpointRoute
  '/api/public/jobs/claim': typeof ApiPublicJobsClaimRoute
  '/api/public/jobs/complete': typeof ApiPublicJobsCompleteRoute
  '/api/public/jobs/continue': typeof ApiPublicJobsContinueRoute
  '/api/public/jobs/event': typeof ApiPublicJobsEventRoute
  '/api/public/jobs/index-batch': typeof ApiPublicJobsIndexBatchRoute
  '/api/public/jobs/index-progress': typeof ApiPublicJobsIndexProgressRoute
  '/api/public/jobs/kaggle': typeof ApiPublicJobsKaggleRoute
  '/api/public/jobs/log': typeof ApiPublicJobsLogRoute
  '/api/public/jobs/new-messages': typeof ApiPublicJobsNewMessagesRoute
  '/api/public/jobs/reference': typeof ApiPublicJobsReferenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/api/public/jobs/checkpoint': typeof ApiPublicJobsCheckpointRoute
  '/api/public/jobs/claim': typeof ApiPublicJobsClaimRoute
  '/api/public/jobs/complete': typeof ApiPublicJobsCompleteRoute
  '/api/public/jobs/continue': typeof ApiPublicJobsContinueRoute
  '/api/public/jobs/event': typeof ApiPublicJobsEventRoute
  '/api/public/jobs/index-batch': typeof ApiPublicJobsIndexBatchRoute
  '/api/public/jobs/index-progress': typeof ApiPublicJobsIndexProgressRoute
  '/api/public/jobs/kaggle': typeof ApiPublicJobsKaggleRoute
  '/api/public/jobs/log': typeof ApiPublicJobsLogRoute
  '/api/public/jobs/new-messages': typeof ApiPublicJobsNewMessagesRoute
  '/api/public/jobs/reference': typeof ApiPublicJobsReferenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/github/callback': typeof ApiGithubCallbackRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/api/public/jobs/checkpoint': typeof ApiPublicJobsCheckpointRoute
  '/api/public/jobs/claim': typeof ApiPublicJobsClaimRoute
  '/api/public/jobs/complete': typeof ApiPublicJobsCompleteRoute
  '/api/public/jobs/continue': typeof ApiPublicJobsContinueRoute
  '/api/public/jobs/event': typeof ApiPublicJobsEventRoute
  '/api/public/jobs/index-batch': typeof ApiPublicJobsIndexBatchRoute
  '/api/public/jobs/index-progress': typeof ApiPublicJobsIndexProgressRoute
  '/api/public/jobs/kaggle': typeof ApiPublicJobsKaggleRoute
  '/api/public/jobs/log': typeof ApiPublicJobsLogRoute
  '/api/public/jobs/new-messages': typeof ApiPublicJobsNewMessagesRoute
  '/api/public/jobs/reference': typeof ApiPublicJobsReferenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/chat'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/github/callback'
    | '/chat/'
    | '/api/public/jobs/checkpoint'
    | '/api/public/jobs/claim'
    | '/api/public/jobs/complete'
    | '/api/public/jobs/continue'
    | '/api/public/jobs/event'
    | '/api/public/jobs/index-batch'
    | '/api/public/jobs/index-progress'
    | '/api/public/jobs/kaggle'
    | '/api/public/jobs/log'
    | '/api/public/jobs/new-messages'
    | '/api/public/jobs/reference'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/api/chat'
    | '/chat/$threadId'
    | '/api/github/callback'
    | '/chat'
    | '/api/public/jobs/checkpoint'
    | '/api/public/jobs/claim'
    | '/api/public/jobs/complete'
    | '/api/public/jobs/continue'
    | '/api/public/jobs/event'
    | '/api/public/jobs/index-batch'
    | '/api/public/jobs/index-progress'
    | '/api/public/jobs/kaggle'
    | '/api/public/jobs/log'
    | '/api/public/jobs/new-messages'
    | '/api/public/jobs/reference'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/chat'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/api/github/callback'
    | '/_authenticated/chat/'
    | '/api/public/jobs/checkpoint'
    | '/api/public/jobs/claim'
    | '/api/public/jobs/complete'
    | '/api/public/jobs/continue'
    | '/api/public/jobs/event'
    | '/api/public/jobs/index-batch'
    | '/api/public/jobs/index-progress'
    | '/api/public/jobs/kaggle'
    | '/api/public/jobs/log'
    | '/api/public/jobs/new-messages'
    | '/api/public/jobs/reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGithubCallbackRoute: typeof ApiGithubCallbackRoute
  ApiPublicJobsCheckpointRoute: typeof ApiPublicJobsCheckpointRoute
  ApiPublicJobsClaimRoute: typeof ApiPublicJobsClaimRoute
  ApiPublicJobsCompleteRoute: typeof ApiPublicJobsCompleteRoute
  ApiPublicJobsContinueRoute: typeof ApiPublicJobsContinueRoute
  ApiPublicJobsEventRoute: typeof ApiPublicJobsEventRoute
  ApiPublicJobsIndexBatchRoute: typeof ApiPublicJobsIndexBatchRoute
  ApiPublicJobsIndexProgressRoute: typeof ApiPublicJobsIndexProgressRoute
  ApiPublicJobsKaggleRoute: typeof ApiPublicJobsKaggleRoute
  ApiPublicJobsLogRoute: typeof ApiPublicJobsLogRoute
  ApiPublicJobsNewMessagesRoute: typeof ApiPublicJobsNewMessagesRoute
  ApiPublicJobsReferenceRoute: typeof ApiPublicJobsReferenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/api/github/callback': {
      id: '/api/github/callback'
      path: '/api/github/callback'
      fullPath: '/api/github/callback'
      preLoaderRoute: typeof ApiGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/checkpoint': {
      id: '/api/public/jobs/checkpoint'
      path: '/api/public/jobs/checkpoint'
      fullPath: '/api/public/jobs/checkpoint'
      preLoaderRoute: typeof ApiPublicJobsCheckpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/claim': {
      id: '/api/public/jobs/claim'
      path: '/api/public/jobs/claim'
      fullPath: '/api/public/jobs/claim'
      preLoaderRoute: typeof ApiPublicJobsClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/complete': {
      id: '/api/public/jobs/complete'
      path: '/api/public/jobs/complete'
      fullPath: '/api/public/jobs/complete'
      preLoaderRoute: typeof ApiPublicJobsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/continue': {
      id: '/api/public/jobs/continue'
      path: '/api/public/jobs/continue'
      fullPath: '/api/public/jobs/continue'
      preLoaderRoute: typeof ApiPublicJobsContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/event': {
      id: '/api/public/jobs/event'
      path: '/api/public/jobs/event'
      fullPath: '/api/public/jobs/event'
      preLoaderRoute: typeof ApiPublicJobsEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/index-batch': {
      id: '/api/public/jobs/index-batch'
      path: '/api/public/jobs/index-batch'
      fullPath: '/api/public/jobs/index-batch'
      preLoaderRoute: typeof ApiPublicJobsIndexBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/index-progress': {
      id: '/api/public/jobs/index-progress'
      path: '/api/public/jobs/index-progress'
      fullPath: '/api/public/jobs/index-progress'
      preLoaderRoute: typeof ApiPublicJobsIndexProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/kaggle': {
      id: '/api/public/jobs/kaggle'
      path: '/api/public/jobs/kaggle'
      fullPath: '/api/public/jobs/kaggle'
      preLoaderRoute: typeof ApiPublicJobsKaggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/log': {
      id: '/api/public/jobs/log'
      path: '/api/public/jobs/log'
      fullPath: '/api/public/jobs/log'
      preLoaderRoute: typeof ApiPublicJobsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/new-messages': {
      id: '/api/public/jobs/new-messages'
      path: '/api/public/jobs/new-messages'
      fullPath: '/api/public/jobs/new-messages'
      preLoaderRoute: typeof ApiPublicJobsNewMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs/reference': {
      id: '/api/public/jobs/reference'
      path: '/api/public/jobs/reference'
      fullPath: '/api/public/jobs/reference'
      preLoaderRoute: typeof ApiPublicJobsReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGithubCallbackRoute: ApiGithubCallbackRoute,
  ApiPublicJobsCheckpointRoute: ApiPublicJobsCheckpointRoute,
  ApiPublicJobsClaimRoute: ApiPublicJobsClaimRoute,
  ApiPublicJobsCompleteRoute: ApiPublicJobsCompleteRoute,
  ApiPublicJobsContinueRoute: ApiPublicJobsContinueRoute,
  ApiPublicJobsEventRoute: ApiPublicJobsEventRoute,
  ApiPublicJobsIndexBatchRoute: ApiPublicJobsIndexBatchRoute,
  ApiPublicJobsIndexProgressRoute: ApiPublicJobsIndexProgressRoute,
  ApiPublicJobsKaggleRoute: ApiPublicJobsKaggleRoute,
  ApiPublicJobsLogRoute: ApiPublicJobsLogRoute,
  ApiPublicJobsNewMessagesRoute: ApiPublicJobsNewMessagesRoute,
  ApiPublicJobsReferenceRoute: ApiPublicJobsReferenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
